package com.mybatismbg.testmybatismbg.mappers;

import com.mybatismbg.testmybatismbg.bean.Jobs;
import com.mybatismbg.testmybatismbg.bean.JobsExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface JobsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs
     *
     * @mbg.generated
     */
    long countByExample(JobsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs
     *
     * @mbg.generated
     */
    int deleteByExample(JobsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs
     *
     * @mbg.generated
     */
    int insert(Jobs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs
     *
     * @mbg.generated
     */
    int insertSelective(Jobs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs
     *
     * @mbg.generated
     */
    List<Jobs> selectByExample(JobsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs
     *
     * @mbg.generated
     */
    Jobs selectByPrimaryKey(String jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Jobs record, @Param("example") JobsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Jobs record, @Param("example") JobsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Jobs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Jobs record);
}