# 配置数据源的连接信息
spring:
  datasource:
    # 设置初始化大小，最小，最大,下面这些配置是针对druid数据源的
    initialSize: 10
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 6000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    username: root
    password: 158293
    url: jdbc:mysql:///myemployees?serverTimezone=GMT&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#  cache:
#    ehcache:
#      config: classpath:ehcache.xml
#    type: ehcache
logging:
  #配置日志的等级,可以输出发送sql的日志
  level: {com.mybatismbg.testmybatismbg.mappers: DEBUG}
mybatis:
  configuration:
    map-underscore-to-camel-case: true
elasticsearch:
    hostname: 192.168.43.245
    port: 9200
    scheme: http

