package com.mybatismbg.testmybatismbg.bean;

import java.io.Serializable;

public class Jobs implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobs.job_id
     *
     * @mbg.generated
     */
    private String jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobs.job_title
     *
     * @mbg.generated
     */
    private String jobTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobs.min_salary
     *
     * @mbg.generated
     */
    private Integer minSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobs.max_salary
     *
     * @mbg.generated
     */
    private Integer maxSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jobs
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobs.job_id
     *
     * @return the value of jobs.job_id
     * @mbg.generated
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobs.job_id
     *
     * @param jobId the value for jobs.job_id
     * @mbg.generated
     */
    public void setJobId(String jobId) {
        this.jobId = jobId == null ? null : jobId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobs.job_title
     *
     * @return the value of jobs.job_title
     * @mbg.generated
     */
    public String getJobTitle() {
        return jobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobs.job_title
     *
     * @param jobTitle the value for jobs.job_title
     * @mbg.generated
     */
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle == null ? null : jobTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobs.min_salary
     *
     * @return the value of jobs.min_salary
     * @mbg.generated
     */
    public Integer getMinSalary() {
        return minSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobs.min_salary
     *
     * @param minSalary the value for jobs.min_salary
     * @mbg.generated
     */
    public void setMinSalary(Integer minSalary) {
        this.minSalary = minSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobs.max_salary
     *
     * @return the value of jobs.max_salary
     * @mbg.generated
     */
    public Integer getMaxSalary() {
        return maxSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobs.max_salary
     *
     * @param maxSalary the value for jobs.max_salary
     * @mbg.generated
     */
    public void setMaxSalary(Integer maxSalary) {
        this.maxSalary = maxSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", jobId=").append(jobId);
        sb.append(", jobTitle=").append(jobTitle);
        sb.append(", minSalary=").append(minSalary);
        sb.append(", maxSalary=").append(maxSalary);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}