package com.mybatismbg.testmybatismbg.bean;

import java.io.Serializable;

public class Locations implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locations.location_id
     *
     * @mbg.generated
     */
    private Integer locationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locations.street_address
     *
     * @mbg.generated
     */
    private String streetAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locations.postal_code
     *
     * @mbg.generated
     */
    private String postalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locations.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locations.state_province
     *
     * @mbg.generated
     */
    private String stateProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locations.country_id
     *
     * @mbg.generated
     */
    private String countryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table locations
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locations.location_id
     *
     * @return the value of locations.location_id
     * @mbg.generated
     */
    public Integer getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locations.location_id
     *
     * @param locationId the value for locations.location_id
     * @mbg.generated
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locations.street_address
     *
     * @return the value of locations.street_address
     * @mbg.generated
     */
    public String getStreetAddress() {
        return streetAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locations.street_address
     *
     * @param streetAddress the value for locations.street_address
     * @mbg.generated
     */
    public void setStreetAddress(String streetAddress) {
        this.streetAddress = streetAddress == null ? null : streetAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locations.postal_code
     *
     * @return the value of locations.postal_code
     * @mbg.generated
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locations.postal_code
     *
     * @param postalCode the value for locations.postal_code
     * @mbg.generated
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode == null ? null : postalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locations.city
     *
     * @return the value of locations.city
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locations.city
     *
     * @param city the value for locations.city
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locations.state_province
     *
     * @return the value of locations.state_province
     * @mbg.generated
     */
    public String getStateProvince() {
        return stateProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locations.state_province
     *
     * @param stateProvince the value for locations.state_province
     * @mbg.generated
     */
    public void setStateProvince(String stateProvince) {
        this.stateProvince = stateProvince == null ? null : stateProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locations.country_id
     *
     * @return the value of locations.country_id
     * @mbg.generated
     */
    public String getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locations.country_id
     *
     * @param countryId the value for locations.country_id
     * @mbg.generated
     */
    public void setCountryId(String countryId) {
        this.countryId = countryId == null ? null : countryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locations
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", locationId=").append(locationId);
        sb.append(", streetAddress=").append(streetAddress);
        sb.append(", postalCode=").append(postalCode);
        sb.append(", city=").append(city);
        sb.append(", stateProvince=").append(stateProvince);
        sb.append(", countryId=").append(countryId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}